### ISSUE TITLE
Build Failed while deploying vercel

### ISSUE THREAD

**Issue by sprupak07** [vendz/fmovies-api#1]
Build Failed
The result of "builder.build" must include an `output` property for "@liudonghua123/now-flask".

**Comment by vendz** [comment]
> Build Failed The result of "builder.build" must include an `output` property for "@liudonghua123/now-flask".

if you are trying to deploy on vercel then make a file `vercel.json` and add the following code to it

```json
{
    "name": "Fmovies-api",
    "version": 2,
    "builds": [
        { "src": "*.py", "use": "@liudonghua123/now-flask" }
    ],
    "routes": [
        { "src": "(.*)", "dest": "app.py" }
    ]
}
```
